### ISSUE TITLE
Problems with Zeroconf

### ISSUE THREAD

**Issue by krantzet** [woutervanwijk/Pi-MusicBox#301]
I am running the latest release (0.6) on a rasberry pi 2 and it works great. I am trying to get two Android apps from Google Play to work with it - Remotedy and Mopidy Mobile. Both uses ZeroConf. It seems like there is some problems with zeroconf even though it's enabled in the config-file:

[http]
enabled = true
hostname =:: 
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

I've also tried 0.0.0.0 on hostname.

Remotedy just says that it can't find any hosts. Mopidy Mobile complains about zeroconf and that is not running. All Web Extensions are working, i.e. Musicbox.local/moped but for Android I would like to try these apps. Any ideas?

(I know Android cant access musicbox.local, so I am trying to connect to the IP-address)

**Comment by kingosticks** [comment]
Musicbox doesn't use Mopidy's zeroconf and instead configures it as a separate service. So it is supposed to be disabled in settings.ini (as the comment there should state). However, those apps use the websocket zeroconf advertisement which musicbox doesn't provide. See https://github.com/woutervanwijk/Pi-MusicBox/issues/291. Will be fixed in the next version when back from holidays.
